server:
  port: 8181


spring:
  application:
    name: attendee-service
  jpa:
    hibernate:
      ddl-auto: update

---

spring:
  profiles: local
  datasource:
    url: jdbc:postgresql://localhost:5432/attendee
    username: vti
    password: vti
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

---

spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:attendee_service
    username: sa
    driverClassName: org.h2.Driver
    platform: h2
